FROM nginx:1.16
COPY static-html-directory /usr/share/nginx/html
docker run --name tmp-nginx-container -d nginx \
docker cp tmp-nginx-container:/etc/nginx/nginx.conf /host/path/nginx.conf \
docker rm -f tmp-nginx-container
